apiVersion: v1
kind: ServiceAccount
metadata:
  name: veganactivist-frontend-sa
  namespace: {{ .Values.environment }}
  labels:
    app: veganactivist
    type: frontend
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: veganactivist-frontend
  namespace: {{ .Values.environment }}
  labels:
    app: veganactivist
    type: frontend
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: veganactivist
      type: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: veganactivist
        type: frontend
      annotations:
        git-commit: {{ .Values.gitCommit }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "doks.digitalocean.com/node-pool"
                    operator: In
                    values:
                      - "apps-2vcpu-2-5ram"
      serviceAccountName: veganactivist-frontend-sa
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: veganactivist-frontend
  namespace: {{ .Values.environment }}
  labels:
    app: veganactivist
    type: frontend
spec:
  selector:
    app: veganactivist
    type: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  sessionAffinity: None
  type: ClusterIP
