apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: veganactivist-test-lets-encrypt-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: fonjallaz97@gmail.com
    privateKeySecretRef:
      name: veganactivist-test-lets-encrypt-issuer
    solvers:
    - selector:
        dnsNames:
        - 'test.veganactivist.ch'
      dns01:
        cloudflare:
          email: fonjallaz97@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
